In [1]:
# Import Libraries
import pandas as pd
import numpy as np
# import numpy
# save numpy array as csv file
from numpy import asarray
from numpy import savetxt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
# Print only 5000 rows for smaller sample
df_5000 = pd.read_csv('df5000ml.csv')
df_5000.head(1)

index  brewery_id     brewery_name          review_time  review_overall  \
0      0       10325  Vecchio Birraio  2009-02-16 20:57:03             1.5   

   review_aroma  review_appearance review_profilename  beer_style  \
0           2.0                2.5            stcules  Hefeweizen   

   review_palate  review_taste     beer_name  beer_abv  beer_beerid  \
0            1.5           1.5  Sausa Weizen       5.0        47986   

                    combined_features  
0  Hefeweizen Vecchio Birraio stcules

In [3]:
sample_df = df_5000.sample(n=500)

In [5]:
df_5000 = sample_df

In [6]:
# Convert a collection of text to a matrix of token counts

count_matrix = CountVectorizer().fit_transform(df_5000["combined_features"])

In [7]:
# Get the cosine similarity matrix from the count matrix
cosine_sim = cosine_similarity(count_matrix)
# print(cosine_sim)

In [8]:
cosine_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.13363062],
       [0.        , 1.        , 0.4       , ..., 0.        , 0.        ,
        0.16903085],
       [0.        , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.16903085],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.13363062, 0.16903085, 0.16903085, ..., 0.        , 0.        ,
        1.        ]])

In [9]:
# # cosine_sim
# # cosine_sim.savetxt('cosine5000.csv')
# datadump = np.asarray(cosine_sim)
# # np.savetxt('cosine5000.csv', cosine_sim, delimiter=',')
# datadump
# # np.savetxt("cosine5000.csv", [datadump], delimiter=",")

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.13363062],
       [0.        , 1.        , 0.4       , ..., 0.        , 0.        ,
        0.16903085],
       [0.        , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.16903085],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.13363062, 0.16903085, 0.16903085, ..., 0.        , 0.        ,
        1.        ]])

In [10]:
# # save numpy array as npy file
# from numpy import asarray
# from numpy import save
# # define data
# data = datadump
# # save to npy file
# save('data.npy', data)

In [ ]:
# from numpy import asarray
# from numpy import savez_compressed
# # define data
# data = datadump
# # save to npy file
# savez_compressed('data.npz', data)

In [2]:
# # load numpy array from npz file
# from numpy import load
# # load dict of arrays
# dict_data = load('data.npz')
# # extract the first array
# data1 = dict_data['arr_0']
# # print the array
# print(dict_data)

In [ ]:
# datadump

In [5]:
# print(data1)

[[1.         0.61237244 0.61237244 ... 0.         0.20412415 0.        ]
 [0.61237244 1.         0.5        ... 0.         0.         0.15430335]
 [0.61237244 0.5        1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.6172134  0.57142857]
 [0.20412415 0.         0.         ... 0.6172134  1.         0.6172134 ]
 [0.         0.15430335 0.         ... 0.57142857 0.6172134  1.        ]]


In [11]:
# # Helper function to get the title from the index
# def get_title_from_index (index):
#     return df_5000[df_5000.index == index]["beer_name"].values[0]

# # # Helper function to get the index from the title
# def get_index_from_title(beer_name):
#     return df_5000[df_5000.beer_name == beer_name]["index"].values[0]

In [12]:
# df_5000["index"][1]

KeyError: 1

In [ ]:
df_5000["beer_name"][1]

In [ ]:
# Get the title of the beer that the user likes
# beer_user_likes = input("Beer Name: ")
beer_user_likes = input("Beer Name: ")

# Find that movies index
beer_index = get_index_from_title(beer_user_likes)

In [ ]:
beer_index

In [ ]:
# Enumerate through all the similarity scores of the beer_user_likes to make
# a tuple of "movie_index" and similarity scores
# NOTE: we will return a list of tuples in the form (movie_index, similarity score)

similar_beers = list( enumerate(cosine_sim[beer_index]) )

In [ ]:
similar_beers

In [ ]:
# Sort the list of silimar movies sccording to the similarity scores in decending order
sorted_similar_beers = sorted(similar_beers,key = lambda x:x[1], reverse = True)[1:]


In [ ]:
sorted_similar_beers

In [ ]:
converted = [list(x) for x in sorted_similar_beers]
converted[1]

In [ ]:
# tuplex = converted
# tuplex = sorted_similar_beers
# tuplex = tuplex[:1] + tuplex[2:] 
# tuplex

In [ ]:
i=0
eliebeers =[]
print(f"The top 5 beers similar to {beer_user_likes} are: ")
for element in sorted_similar_beers:
    eliebeers.append(element[0])
#     print(df_5000.loc[df_5000['index']==eliebeers])
    print((element[0]))
#     print((df_5000.loc[df_5000['index']==element[0]]))
    i=i+1
    if i>=5:
        break
        
#List that Captures Index in Matrix of Similar Beers
bambam =[]

for x in eliebeers:
    row = df_5000.loc[df_5000['index']==x, ['beer_name']].values
    bambam.append(row[0][0])

In [ ]:
bambam